all: programa

programa: ejercicio1.o ejercicio2.o ejercicio3.o ejercicio4.o ejercicio5.o ejercicio6.o ejercicio7.o ejercicio8.o ejercicio9.o ejercicio10.o
	g++ ejercicio1.o ejercicio2.o ejercicio3.o ejercicio4.o ejercicio5.o ejercicio6.o ejercicio7.o ejercicio8.o ejercicio9.o ejercicio10.o -o programa

ejercicio1.o: ejercicio1.cc
	g++ -c ejercicio1.cc

ejercicio2.o: ejercicio2.cc
	g++ -c ejercicio2.cc

ejercicio3.o: ejercicio3.cc
	g++ -c ejercicio3.cc

ejercicio4.o: ejercicio4.cc
	g++ -c ejercicio4.cc

ejercicio5.o: ejercicio5.cc
	g++ -c ejercicio5.cc

ejercicio6.o: ejercicio6.cc
	g++ -c ejercicio6.cc

ejercicio7.o: ejercicio7.cc
	g++ -c ejercicio7.cc

ejercicio8.o: ejercicio8.cc
	g++ -c ejercicio8.cc

ejercicio9.o: ejercicio9.cc
	g++ -c ejercicio9.cc

ejercicio10.o: ejercicio10.cc
	g++ -c ejercicio10.cc

clean:
	rm -rf *o programa


