programa: dividers.o temperatures.o suma_de_los_tres_ultimos_digitos.o suma_de_digitos.o time_decomposition.o leap_year.o cuadrado_asteriscos.o longest_shortest.o random_numbers.o statistics.o collatz.o
	g++ -o dividers.o temperatures.o suma_de_los_tres_ultimos_digitos.o suma_de_digitos.o time_decomposition.o leap_year.o cuadrado_asteriscos.o longest_shortest.o random_numbers.o statistics.o collatz.o -o programa

dividers.o: dividers.cc
	g++ -c dividers.cc

temperatures.o: temperatures.cc
	g++ -c temperatures.cc

suma_de_los_tres_ultimos_digitos.o: suma_de_los_tres_ultimos_digitos.cc
	g++ -c suma_de_los_tres_ultimos_digitos.cc

suma_de_digitos.o: suma_de_digitos.cc
	g++ -c suma_de_digitos.cc

time_decomposition.o: time_decomposition.cc
	g++ -c time_decomposition.cc

leap_year.o: leap_year.cc
	g++ -c leap_year.cc

cuadrado_asteriscos.o: cuadrado_asteriscos.cc
	g++ -c cuadrado_asteriscos.cc

longest_shortest.o: longest_shortest.cc
	g++ -c longest_shortest.cc

random_numbers.o: random_numbers.cc
	g++ -c random_numbers.cc

statistics.o: statistics.cc
	g++ -c statistics.cc

collatz.o: collatz.cc
	g++ -c collatz.cc

clean:
	rm -rf *.o programa


